### ISSUE TITLE
Failed to activate the status-bar package

### ISSUE THREAD

**Issue by udoyen** [atom/status-bar#160]
[Enter steps to reproduce below:]

1. create git repo on computer
2. add files and then commit
3. create and add remote repo
4. close and relaunch atom

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.0

### Stack Trace

Failed to activate the status-bar package

```
At Cannot read property 'onDidChangeStatuses' of undefined

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at status-bar-git.GitView.subscribeToRepositories (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:106:61)
    at status-bar-git.GitView.initialize (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:32:12)
    at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/main.js:67:16)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-csslint"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0
emmet, v2.4.3
language-blade, v0.25.3
laravel, v0.7.0
terminal-plus, v0.14.5
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please re-download Atom 1.8.0.  Apologies for the inconvenience.

**Comment by rochford77** [comment]
I also had this issue. It also was happening in nuclide (different error, was still complaining about mercurial). 

first of all, I got just reinstalled my os (OS X El Captain) last night and never had this problem before. I downloaded Mercurial from brew, cloned my repos set-up Atom, only to run into this problem. Basically any HG related extension was causing Atom to freak out. Here is how i fixed it:

Uninstalled/Reinstalled Atom (with Atom-HG), didn't fix.

uninstalled Atom, deleted .atom (hidden) folder from home folder, rebooted, reinstalled Atom (and atom-hg), didn't fix.

uninstalled Atom, deleted .atom, uninstalled Mercurial (brew), deleted my repos from my machine, rebooted, installed Mercurial (not using brew), installed Atom (and atom-hg), then pulled my repos in and its all golden. 

hope this helps.

**Comment by elevow** [comment]
Duplicated on Windows 7 with v1.9

**Comment by Aetheus** [comment]
Duplicated on Windows 7 with 1.9.1. Much like @rochford77 , the issue I encountered seems to be caused by a package for a VCS (in this case, SVN).

Steps to reproduce:
1. Install svn package (https://atom.io/packages/svn)
2. Launch atom.

Steps to avoid issue:
1. Disable svn package.
2. Relaunch atom.

**Comment by Rubytor** [comment]
Excuse me, why is this issue "CLOSED"?? I'm getting the same problem

Just add git repository and the re-launch atom, It stuck with:

Cannot read property 'onDidChangeStatuses' of undefined

If I close atom and change directory to another without git repository, atom open perfectly.

I already tried uninstalling it from package manager, and removing all the folders, including /home/user/.atom

But the problem persist after a clean installation.

I'm using ubuntu 14.04, so .deb package downloaded from atom.io

If there are any solution.

Thanks.

**Comment by rochford77** [comment]
Rubytor It's closed because it was an intentional break. See the release notes from 1.9.

>Removal of GitRepositoryAsync
Earlier this year, we added an experimental async API for interacting with Git repositories based on libgit2 called GitRepositoryAsync. We never officially made this API public, but some package authors started using it anyway based on examples in our bundled packages.
Unfortunately, our bindings to libgit2 were causing Atom’s helper processes to become unstable, leading to hard crashes. We apologize to any package authors who may have switched to these new APIs, but we’ve been forced to back out the async APIs. We’ll be trying again soon with a new approach for interacting with Git that’s more stable.
For a more comprehensive list of improvements and bug fixes, please check out the release notes! :memo:

My very uninformed take on it is that the issue is not with status bar. The issue is with any VCS community package using hooks to a API that was removed in atom 1.9. it is up to the package maintainers to fix the way their packages work. 

Also, see issue 154 and 161 as they are the same thing.

Either revert to 1.8, or disable any conflicting packages and wait for a fix.

**Comment by dcholth** [comment]
@rochford77 Specifically the issue is probably with atom-hg.  This appears to be known issue with that package and Atom 1.9.  [https://github.com/victor-torres/atom-hg/issues](url)
