### ISSUE TITLE
Add project name to .current-path

### ISSUE THREAD

**Issue by mz103** [atom/status-bar#180]
A lot of us have a lot of projects that have a similar structure (i.e. atom packages), with similarly named files (i.e. `package.json`), and it'd be really nice if the project name was included at the bottom of the status bar in the `.current-path` selector's textContent.

For example, right now it's: `package.json`

I'm suggesting: `status-bar/package.json` which would make a lot more sense, and give the developer context

**Comment by lee-dohm** [comment]
Thanks for taking the time to contribute!

I have passed along the information to the maintainers team for review after the holidays. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. 

We do include the project name in the title bar currently which is a help when swapping around via <kbd>Cmd+Tab</kbd> on macOS or <kbd>Alt+Tab</kbd> on other platforms.
