### ISSUE TITLE
[Suggestion] Switch from underline to highlight for hover style of status bar panels

### ISSUE THREAD

**Issue by mehcode** [atom/status-bar#196]
**Current**
![screen shot 2017-06-13 at 4 54 30 am](https://user-images.githubusercontent.com/753919/27081266-6848b1ca-4ff4-11e7-85ec-1df441de8bd9.png)

**Proposed**
![screen shot 2017-06-13 at 4 54 12 am](https://user-images.githubusercontent.com/753919/27081265-6841b474-4ff4-11e7-9078-a5a97874ad49.png)

---

The motivating factor is primarily that underline is currently the predominating "this is how it should look on the status bar" but underline doesn't really make sense (to me) for clicking a panel. 

There are some packages that are having issues with it:
 - https://github.com/steelbrain/linter-ui-default/issues/351 (concern [from me] that 3 numbers being underlined looks unruly all together)
 - https://github.com/atom/github/pull/445 (concern over the push/pull with no numbers not being able to give an underline)

**Comment by simurai** [comment]
👍  On the suggestion. Maybe could be like this:

- Use the background hover style as **default**.
- Introduce a `is-external-link` or similar class. This would show the current underline, but should **only** be used if it links to an external browser. I think none of the current bundled Atom packages do that.

**Comment by simurai** [comment]
Tried to change it in this package, but it's a bit a "wild west" because every package adds their own element and class names and there isn't a convention/API.

![image](https://user-images.githubusercontent.com/378023/27678212-60c505ae-5cef-11e7-82d6-75d3f2c21ffc.png)

Also, lots of themes add their own styling. So changing it in this package would break some themes. For now I'll change it for the One themes.
