### ISSUE TITLE
Option to disable git functionality

### ISSUE THREAD

**Issue by JordanMajd** [atom/status-bar#226]
Git is very slow over remote connections and I often times work over SSHFS. In order for Atom to be somewhat responsive, I find myself disabling every single package that makes use of git.

Ideally, I would not need to disable `status-bar` and would only need to turn off the git functionality.

**Comment by rsese** [comment]
Thanks for the report - the performance issue with Git and working over SSHFS has an issue at https://github.com/atom/atom/issues/2456 (and the related request to be able to disable the Git integration is referenced in that issue and others like https://github.com/atom/tree-view/issues/784 for example, though it looks like you found that issue).  We'll go ahead and close in favor of those issues, but you can subscribe to https://github.com/atom/atom/issues/2456 for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by JordanMajd** [comment]
@unluisco Thanks for the suggestion. However, the git functionality in the status bar is unrelated to the github package.

@rsese Thanks for the informative update; I will subscribe to those tickets.
