### ISSUE TITLE
Deprecation Cop warning: TextBuffer.on is deprecated.

### ISSUE THREAD

**Issue by bjmiller** [atom/status-bar#74]
TextBuffer::on is deprecated. Use event subscription methods instead.
```
TextBuffer.on (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1194:16)
status-bar.subscribeAllToBuffer (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/status-bar-view.js:152:35)
<unknown> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/status-bar-view.js:41:17)
Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
```

**Comment by bjmiller** [comment]
Is anyone looking at this?

**Comment by thomasjo** [comment]
Not to my knowledge. I might be wrong, but I don't think there are any plans for replacing this functionality. AFAIK no core package relies on this. /cc @atom/feedback 

---
For reference, the problem lies within these [three functions](https://github.com/atom/status-bar/blob/84100eab9e3cd2ffa728c1c3e561147536865976/lib/status-bar-view.coffee#L96-L108).

**Comment by bjmiller** [comment]
Well, if it's dead/unused code, then it can simply be wiped.  That would solve the problem stemming from the warning.

**Comment by izuzak** [comment]
@bjmiller Can you clarify which version of Atom you're using, which OS, and how exactly are you able to reproduce this deprecation? Are you able to reproduce it in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) as well? I'm having trouble trigger that deprecation, so I'm wondering what you're doing differently.

Also, that deprecation seems to be triggered in TextBuffer [here](https://github.com/atom/text-buffer/blob/5ece467ed114da25fe3f7bdc9ad1613ddd7e967e/src/text-buffer.coffee#L1458). Notice that it's an `else` block after a long list of events which TextBuffer supports. That makes me think that something (not sure what, because I can't reproduce the deprecation) is using the status bar to subscribe to an event which is not listed.

**Comment by bjmiller** [comment]
I stopped getting it, which suggests to me that it's one if the packages left that hasn't updated - and therefore isn't running.  If I had to guess, I'd say it was the `sloc` package.  It makes heavy use of the status bar, and it already has 14 or so other deprecations.

**Comment by izuzak** [comment]
Thanks for those details, @bjmiller. 

Just tried installing `atom-sloc` (after overriding the block in Atom), and it does cause a deprecation like that:

![screen shot 2015-06-08 at 13 44 33](https://cloud.githubusercontent.com/assets/38924/8034060/90f78ec4-0de4-11e5-8f88-c2f0b62c8b59.png)

That deprecation is correctly attributed to the `atom-sloc` package in Deprecation Cop and the line in the deprecation [points to the cause](https://github.com/sgade/atom-sloc/blob/05ee6fa9972d9d1c8ca939115baa4b24a11a1962/lib/sloc-view.coffee#L20). 

As far as I can tell, there's no problem with status-bar here, but please let me know if you still think there is, @bjmiller.
